$(document).ready(function(){
    $('.js-toggle-class').click(function(){
        $('.div-to-center').addClass('new-hidden');
        $('.about-me-toggle-page').removeClass('new-hidden');
        console.log("clicked");
    });
});
$(document).ready(function(){
    $('.js-close-button').click(function(){
        $('.div-to-center').removeClass('new-hidden');
        $('.about-me-toggle-page').addClass('new-hidden');
    })
})
$(document).ready(function(){
    $('.js-close-button').mouseenter(function(){
        $('span').addClass('rotate')
        console.log('entered');
    })
});